import {createAction} from 'redux-actions';

interface Actions {
  [key: string]: any,
}

export default {
  'PEERS/FETCH': createAction('PEERS/FETCH'),
  'PEERS/FETCHED_SUCCESSFULLY': createAction('PEERS/FETCHED_SUCCESSFULLY'),
  'PEERS/FETCHED_ERROR': createAction('PEERS/FETCHED_ERROR'),
  'PEERS/TREASURY_BALANCE': createAction('PEERS/TREASURY_BALANCE'),
  'PEERS/TREASURY_BALANCE_FETCHED_SUCCESSFULLY': createAction('PEERS/TREASURY_BALANCE_FETCHED_SUCCESSFULLY'),
  'PEERS/TREASURY_BALANCE_FETCHED_ERROR': createAction('PEERS/TREASURY_BALANCE_FETCHED_ERROR'),
} as Actions;
