import {createAction} from 'redux-actions';

interface Actions {
  [key: string]: any,
}

export default {
  'ACCOUNT_TRANSACTIONS/FETCH': createAction('ACCOUNT_TRANSACTIONS/FETCH'),
  'ACCOUNT_TRANSACTIONS/FETCHED_SUCCESSFULLY': createAction('ACCOUNT_TRANSACTIONS/FETCHED_SUCCESSFULLY'),
  'ACCOUNT_TRANSACTIONS/FETCHED_ERROR': createAction('ACCOUNT_TRANSACTIONS/FETCHED_ERROR'),

  'ACCOUNT_TRANSACTIONS/ON_SEARCH_ACCOUNT_CHANGED': createAction('ACCOUNT_TRANSACTIONS/ON_SEARCH_ACCOUNT_CHANGED'),
} as Actions;
